# Generated by Django 4.2.30 on 2026-05-13 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='slug',
            field=models.CharField(choices=[('create', 'CREATE'), ('read', 'READ'), ('update', 'UPDATE'), ('delete', 'DELETE')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='dashboard.action'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='dashboard.resource'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='dashboard.role'),
        ),
    ]
